### ISSUE TITLE
please

### ISSUE THREAD

**Issue by Tokisakix** [JasonW41k3r/db_experiment#1]

**Comment by Tokisakix** [comment]
please use `new` in Cpp or `malloc` in C

```C
int n;
scanf("%d", &n);
int opt[n];
```

(*^_^*)

**Comment by JasonW41k3r** [comment]
Thank you for pointing this out.

I've addressed the issue by replacing the stack allocation with dynamic memory allocation. Here's the updated code:

```c
int n;
scanf("%d", &n);
int *opt = (int *)malloc(n * sizeof(int));
if (opt == NULL) {
    printf("Memory allocation failed.\n");
    return -1;
}
// Remember to free(opt) after usage to avoid memory leaks.
```

Let me know if there's anything else to improve.

**Comment by JasonW41k3r** [comment]
The issue of `buffer_size[ ]` array was handled as well thanks to your reminding.
